parameters:
        swh:
                index: 1
                description: Significant height of combined wind waves and swell
        mwd: 
                index: 2
                description: Mean wave direction
        mwp: 
                index: 3
                description: Mean wave period 
        '004':
                index: 4
                description: Friction velocity
        dwi: 
                index: 5
                description: 10 metre wind direction 
        pp1d: 
                index: 6
                description: Peak wave period
        cdww:
                index: 7
                description: Coefficient of drag with waves
        '008':
                index: 8
                description: Normalised wave stress
        msqs: 
                index: 9
                description: Mean square slope of waves
        wind:
                index: 10
                description: 10 metre wind speed
        shww: 
                index: 11
                description: Significant height of wind waves
        shts:
                index: 12
                description: Significant height of total swell
        mdww:
                index: 13
                description: Mean direction of wind waves 
        mdts:
                index: 14
                description: Mean direction of total swell
        mpww:
                index: 15
                description: Mean period of wind waves
        mpts:
                index: 16
                description: Mean period of total swell
        awh:
                index: 17
                description: Altimeter wave height
        acwh':
                index: 18
                description: Corrected altimeter wave height
        arrc:
                index: 19
                description: Altimeter range correction
        mp1:
                index: 20
                description: Mean wave period based on first moment
        mp2:
                index: 21
                description: Mean zero-crossing wave period
        wdw:
                index: 22
                description: Wave spectral directional width
        p1ww:
                index: 23
                description: Mean wave period based on first moment for wind waves
        p1ps:
                index: 24
                description: Mean wave period based on first moment for swell
        p2ww:
                index: 25
                description: Mean wave period based on second moment for wind waves
        p2ps:
                index: 26
                description: Mean wave period based on second moment for swell
        dwww:
                index: 27
                description: Wave spectral directional width for wind waves
        dwps:
                index: 28
                description: Wave spectral directional width for swell
        wsk :
                index: 29
                description: Wave spectral kurtosis
        bfi:
                index: 30
                description: Benjamin-Feir index
        wsp:
                index: 31
                description: Wave spectral peakedness
        wmb:
                index: 32
                description: Model bathymetry
        hmax:
                index: 33
                description: Maximum individual wave height
        tmax:
                index: 34
                description: Period corresponding to maximum individual wave height
        ust:
                index: 35
                description: U-component stokes drift
        vst:
                index: 36
                description: V-component stokes drift
        ocu:
                index: 37
                description: Eastward sea water velocity
        vcu:
                index: 38
                description: Northward sea water velocity
        phioc:
                index: 39
                description: Normalised energy flux to ocean
        phiaw:
                index: 40
                description: Normalised energy flux to waves
        tauoc:
                index: 41
                description: Normalised momentum flux to ocean
        swh1:
                index: 42
                description: Swell partition 1 wave height
        mwd1:
                index: 43
                description: Swell partition 1 direction
        mwp1:
                index: 44
                description: Swell partition 1 mean period
        swh2:
                index: 45
                description: Swell partition 2 wave height
        mwd2:
                index: 46
                description: Swell partition 2 direction
        mwp2:
                index: 47
                description: Swell partition 2 mean period
        swh3:
                index: 48
                description: Swell partition 3 wave height
        mwd3:
                index: 49
                description: Swell partition 3 direction
        mwp3:
                index: 50
                description: Swell partition 3 mean period
        mswsi:
                index: 51
                description: Mean square strain in ice
        sh10:
                index: 52
                description: Wave height with period > 10s
        rhoao:
                index: 53
                description: Surface air density
        wstar:
                index: 54
                description: Convective velocity scale
        ci:
                index: 55
                description: Sea ice area fraction
        sithick:
                index: 56
                description: Sea ice thickness
        wss:
                index: 57
                description: Spectral skewness
        sic:
                index: 58
                description: Sea ice cover (NEMO)
        '059':
                index: 59
                description: Sea ice thickness (NEMO)
        ucurr:
                index: 60
                description: U-component of current (NEMO)
        vcurr:
                index: 61
                description: V-component of current (NEMO)
        wefxm:
                index: 62
                description: Wave energy flux magnitude
        wefxd':
                index: 63
                description: Wave energy flux direction
        h1012:
                index: 64
                description: Significant wave height 10<=T<=12
        h1214:
                index: 65
                description: Significant wave height 12<=T<=14
        h1417:
                index: 66
                description: Significant wave height 14<=T<=17
        h1721:
                index: 67
                description: Significant wave height 17<=T<=21
        h2125:
                index: 68
                description: Significant wave height 21<=T<=25
        h2530:
                index: 69
                description: Significant wave height 25<=T<=30
        weta:
                index: 70
                description: Wave induced sea level correction
        wraf:
                index: 71
                description: Spectral width index
        wnslc:
                index: 72
                description: Number of freak waves events
        utaua:
                index: 73
                description: U-component atmospheric stress
        vtaua:
                index: 74
                description: V-component atmospheric stress
        utauo:
                index: 75
                description: U-component stress into oceans
        vtauo:
                index: 76
                description: V-component stress into oceans
        wphio:
                index: 77
                description: Turbulence energy flux into oceans
        tdcmax:
                index: 78
                description: Time domain maximum crest height
        tdhmax:
                index: 79
                description: Time domain maximum wave height
        stcmax:
                index: 80
                description: Space time maximum crest type
        sthmax:
                index: 81
                description: Space time maximum wave height
        wcfr:
                index: 82
                description: Whitecap fraction 

