! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE CPGRBOBSTRCT(BLK2GLO, M, K, FIELD)

!****  *CPGRBOBSTRCT* - COPY DECODED OBSTRUCTION COEFFICIENTS TO CORRESPONDING ARRAY

! -------------------------------------------------------------------

USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
USE YOWDRVTYPE  , ONLY : WVGRIDGLO

USE YOWGRID  , ONLY : NPROMA_WAM
USE YOWMPP   , ONLY : IRANK
USE YOWPCONS , ONLY : ZMISS
USE YOWSTAT  , ONLY : IPROPAGS
USE YOWSPEC  , ONLY : NSTART, NEND
USE YOWUBUF  , ONLY : OBSLAT, OBSLON, OBSCOR, OBSRLAT, OBSRLON,  &
                    & KTOIS, KTOOBSTRUCT
USE YOWWIND  , ONLY : NXFFS_LOC, NXFFE_LOC, NYFFS_LOC, NYFFE_LOC

USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

!----------------------------------------------------------------------

IMPLICIT NONE

TYPE(WVGRIDGLO), INTENT(IN)       :: BLK2GLO    !! POINTERS FROM GLOBAL GRID POINTS TO 2-D MAP
INTEGER(KIND=JWIM), INTENT(IN)    :: M          !! FREQUENCY INDEX
INTEGER(KIND=JWIM), INTENT(IN)    :: K          !! DIRECTION INDEX FOR THE OBSTRUCTIONS INPUT 
REAL(KIND=JWRB), DIMENSION(NXFFS_LOC:NXFFE_LOC, NYFFS_LOC:NYFFE_LOC), INTENT(IN) ::  FIELD

INTEGER(KIND=JWIM) :: IJ, IS, IX, IY
INTEGER(KIND=JWIM) :: IOBSRT
INTEGER(KIND=JWIM) :: JKGLO, KIJS, KIJL

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPGRBOBSTRCT',0,ZHOOK_HANDLE)

IS = KTOIS(K,IPROPAGS)

IF ( IS > 0 ) THEN
  IOBSRT = KTOOBSTRUCT(K,IPROPAGS)
  SELECT CASE(IOBSRT)

  CASE(1)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ, IX, IY)
    DO JKGLO = NSTART(IRANK), NEND(IRANK), NPROMA_WAM
      KIJS=JKGLO
      KIJL=MIN(KIJS+NPROMA_WAM-1, NEND(IRANK))
      DO IJ = KIJS, KIJL
        IX = BLK2GLO%IXLG(IJ)
        IY = NGY- BLK2GLO%KXLT(IJ) +1
        IF (FIELD(IX,IY) /= ZMISS) THEN
          OBSLAT(IJ,M,IS) = FIELD(IX,IY)
        ELSE
          OBSLAT(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(2)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ, IX, IY)
    DO JKGLO = NSTART(IRANK), NEND(IRANK), NPROMA_WAM
      KIJS=JKGLO
      KIJL=MIN(KIJS+NPROMA_WAM-1, NEND(IRANK))
      DO IJ = KIJS, KIJL
        IX = BLK2GLO%IXLG(IJ)
        IY = NGY- BLK2GLO%KXLT(IJ) +1
        IF (FIELD(IX,IY) /= ZMISS) THEN
          OBSLON(IJ,M,IS) = FIELD(IX,IY)
        ELSE
          OBSLON(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(3)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ, IX, IY)
    DO JKGLO = NSTART(IRANK), NEND(IRANK), NPROMA_WAM
      KIJS=JKGLO
      KIJL=MIN(KIJS+NPROMA_WAM-1, NEND(IRANK))
      DO IJ = KIJS, KIJL
        IX = BLK2GLO%IXLG(IJ)
        IY = NGY- BLK2GLO%KXLT(IJ) +1
        IF (FIELD(IX,IY) /= ZMISS) THEN
          OBSRLAT(IJ,M,IS) = FIELD(IX,IY)
        ELSE
          OBSRLAT(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(4)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ, IX, IY)
    DO JKGLO = NSTART(IRANK), NEND(IRANK), NPROMA_WAM
      KIJS=JKGLO
      KIJL=MIN(KIJS+NPROMA_WAM-1, NEND(IRANK))
      DO IJ = KIJS, KIJL
        IX = BLK2GLO%IXLG(IJ)
        IY = NGY- BLK2GLO%KXLT(IJ) +1
        IF (FIELD(IX,IY) /= ZMISS) THEN
          OBSRLON(IJ,M,IS) = FIELD(IX,IY)
        ELSE
          OBSRLON(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(5)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ, IX, IY)
    DO JKGLO = NSTART(IRANK), NEND(IRANK), NPROMA_WAM
      KIJS=JKGLO
      KIJL=MIN(KIJS+NPROMA_WAM-1, NEND(IRANK))
      DO IJ = KIJS, KIJL
        IX = BLK2GLO%IXLG(IJ)
        IY = NGY- BLK2GLO%KXLT(IJ) +1
        IF (FIELD(IX,IY) /= ZMISS) THEN
          OBSCOR(IJ,M,IS) = FIELD(IX,IY)
        ELSE
          OBSCOR(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  END SELECT

ENDIF

IF (LHOOK) CALL DR_HOOK('CPGRBOBSTRCT',1,ZHOOK_HANDLE)

END SUBROUTINE CPGRBOBSTRCT
